name: 'Build Android App Bundle'
description: 'Builds a signed Flutter Android App Bundle (AAB) and uploads it as an artifact'

inputs:
  flutter_version:
    description: 'Flutter version to install'
    required: false
    default: '3.24.0'
  java_version:
    description: 'Java version for setup-java'
    required: false
    default: '17'
  keystore_base64:
    description: 'Base64-encoded keystore file (store as secret)'
    required: true
  keystore_password:
    description: 'Keystore password (store as secret)'
    required: true
  key_password:
    description: 'Key password (store as secret)'
    required: true
  key_alias:
    description: 'Key alias (store as secret)'
    required: true
  artifact_name:
    description: 'Name of the upload-artifact for the AAB'
    required: false
    default: 'app-bundle'
  retention_days:
    description: 'Number of days to retain the AAB artifact'
    required: false
    default: '30'

outputs:
  version_name:
    description: 'App version name (e.g. 1.1.0 or 1.0.run_number)'
  version_code:
    description: 'App version code (integer)'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        cache: 'gradle'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: 'stable'

    - name: Get Flutter dependencies
      shell: bash
      run: flutter pub get

    - name: Clean Gradle build
      shell: bash
      run: |
        cd android
        ./gradlew clean --stop || true

    - name: Set version name and code (auto on push)
      id: version
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          VERSION_NAME="${GITHUB_REF#refs/tags/v}"
        else
          VERSION_NAME="1.0.${{ github.run_number }}"
        fi
        VERSION_CODE=$((2 + ${{ github.run_number }}))
        echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
        echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
        sed -i "s/^version: .*/version: ${VERSION_NAME}+${VERSION_CODE}/" pubspec.yaml
        echo "Version: ${VERSION_NAME}+${VERSION_CODE}"
        grep "^version:" pubspec.yaml

    - name: Decode keystore file
      shell: bash
      run: |
        echo "${{ inputs.keystore_base64 }}" | base64 -d > android/app/keystore.jks

    - name: Create key.properties file
      shell: bash
      run: |
        echo "storePassword=${{ inputs.keystore_password }}" > android/key.properties
        echo "keyPassword=${{ inputs.key_password }}" >> android/key.properties
        echo "keyAlias=${{ inputs.key_alias }}" >> android/key.properties
        echo "storeFile=keystore.jks" >> android/key.properties

    - name: Build App Bundle
      shell: bash
      run: flutter build appbundle --release --build-number=${{ steps.version.outputs.version_code }}

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: ${{ inputs.retention_days }}
